language: ruby

cache: bundler
sudo: false

branches:
  - master
  - /^v\d+\.\d+(?:\.\d+)?(?:-\S*)?$/

before_install:
  - "gem update --system --no-doc"
  - "gem install bundler"

bundler_args: "--without development --with ci"

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.13.0
  - jruby-9.2.0.0
  - ruby-head
  - jruby-head

matrix:
  exclude:
    # This one runs separately to send data to CodeClimate
    - rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile

    # It appears that activerecord-jdbc-adapter isn't compatible with 5.2 yet
    - rvm: jruby-9.1.13.0
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: jruby-9.2.0.0
      gemfile: gemfiles/rails_5.2.gemfile

  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
      after_script: "bundle exec codeclimate-test-reporter"

  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
